export const APP_FONT_FAMILY = 'Pretendard GOV';

export const nativeColors = {
  amber50: '#fffbeb',
  amber400: '#fbbf24',
  blue50: '#eff6ff',
  blue500: '#2b7fff',
  blue600: '#155dfc',
  blue700: '#5d718c',
  emerald50: '#ecfdf5',
  emerald500: '#10b981',
  red50: '#fef2f2',
  red500: '#fb2c36',
  red600: '#dc2626',
  slate50: '#f8fafc',
  slate100: '#f1f5f9',
  slate200: '#e2e8f0',
  slate300: '#cbd5e1',
  slate400: '#94a3b8',
  slate500: '#64748b',
  slate600: '#475569',
  slate700: '#334155',
  teal50: '#f0fdfa',
  violet50: '#f5f3ff',
  violet300: '#c4b5fd',
  violet400: '#a78bfa',
  violet500: '#8b5cf6',
};

export const nativeTheme = {
  light: {
    ...nativeColors,
    colorAccent: nativeColors.blue500,
    colorAccentHover: nativeColors.blue600,
    colorAccentPressed: nativeColors.blue600,
    colorAccentSoft: nativeColors.blue50,
    colorBgAccentSoft: nativeColors.blue50,
    colorBgApp: '#ffffff',
    colorBgCard: '#ffffff',
    colorBgDangerSoft: nativeColors.red50,
    colorBgDivider: nativeColors.slate100,
    colorBgInput: nativeColors.slate50,
    colorBgInputFocus: nativeColors.blue50,
    colorBgModal: '#ffffff',
    colorBgScreen: '#ffffff',
    colorBgSurface: '#ffffff',
    colorBgSurfaceElevated: '#ffffff',
    colorBgSurfaceMuted: nativeColors.slate50,
    colorBgSurfacePressed: nativeColors.slate200,
    colorBgTab: '#ffffff',
    colorBgToast: 'rgba(241, 245, 249, 0.86)',
    colorBgToastBorder: 'rgba(255, 255, 255, 0.55)',
    colorBgToolbar: nativeColors.slate50,
    colorBgVioletSoft: nativeColors.violet50,
    colorBorderAccentFocus: 'rgba(43, 127, 255, 0.12)',
    colorBorderAccentSoft: 'rgba(43, 127, 255, 0.08)',
    colorBorderStrong: nativeColors.slate400,
    colorBorderSubtle: nativeColors.slate200,
    colorBorderTabBlur: 'rgba(226, 232, 240, 0.9)',
    colorBorderViolet: nativeColors.violet400,
    colorDanger: nativeColors.red600,
    colorDangerSolid: nativeColors.red500,
    colorOverlayFrost: 'rgba(255, 255, 255, 0.52)',
    colorOverlayScrim: 'rgba(0, 0, 0, 0.3)',
    colorPressOverlaySlate10050: 'rgba(241, 245, 249, 0.5)',
    colorStateLayerAccent: 'rgba(2, 6, 23, 0.12)',
    colorStateLayerStrong: 'rgba(15, 23, 42, 0.1)',
    colorTextAccent: nativeColors.blue500,
    colorTextAccentStrong: nativeColors.blue600,
    colorTextDanger: nativeColors.red600,
    colorTextDisabled: nativeColors.slate400,
    colorTextMuted: nativeColors.slate400,
    colorTextOnAccent: '#ffffff',
    colorTextPrimary: nativeColors.slate700,
    colorTextSecondary: nativeColors.slate600,
    colorTextTertiary: nativeColors.slate500,
    colorTextToast: 'rgb(69, 85, 108)',
    colorTextViolet: nativeColors.violet500,
    colorTextVioletMuted: nativeColors.violet300,
  },
  dark: {
    colorBgApp: '#020617',
    colorBgScreen: '#0f172a',
    colorTextPrimary: '#f1f5f9',
  },
};

export const nativeCssVariables = {
  '--amber-50': nativeTheme.light.amber50,
  '--amber-400': nativeTheme.light.amber400,
  '--blue-50': nativeTheme.light.blue50,
  '--blue-500': nativeTheme.light.blue500,
  '--blue-600': nativeTheme.light.blue600,
  '--blue-700': nativeTheme.light.blue700,
  '--color-accent': nativeTheme.light.colorAccent,
  '--color-accent-hover': nativeTheme.light.colorAccentHover,
  '--color-accent-pressed': nativeTheme.light.colorAccentPressed,
  '--color-accent-soft': nativeTheme.light.colorAccentSoft,
  '--color-accent-solid': nativeTheme.light.colorAccent,
  '--color-bg-accent-soft': nativeTheme.light.colorBgAccentSoft,
  '--color-bg-app': nativeTheme.light.colorBgApp,
  '--color-bg-card': nativeTheme.light.colorBgCard,
  '--color-bg-danger-soft': nativeTheme.light.colorBgDangerSoft,
  '--color-bg-divider': nativeTheme.light.colorBgDivider,
  '--color-bg-input': nativeTheme.light.colorBgInput,
  '--color-bg-input-focus': nativeTheme.light.colorBgInputFocus,
  '--color-bg-modal': nativeTheme.light.colorBgModal,
  '--color-bg-screen': nativeTheme.light.colorBgScreen,
  '--color-bg-surface': nativeTheme.light.colorBgSurface,
  '--color-bg-surface-elevated': nativeTheme.light.colorBgSurfaceElevated,
  '--color-bg-surface-muted': nativeTheme.light.colorBgSurfaceMuted,
  '--color-bg-surface-pressed': nativeTheme.light.colorBgSurfacePressed,
  '--color-bg-tab': nativeTheme.light.colorBgTab,
  '--color-bg-toast': nativeTheme.light.colorBgToast,
  '--color-bg-toast-border': nativeTheme.light.colorBgToastBorder,
  '--color-bg-toolbar': nativeTheme.light.colorBgToolbar,
  '--color-bg-violet-soft': nativeTheme.light.colorBgVioletSoft,
  '--color-border-accent-focus': nativeTheme.light.colorBorderAccentFocus,
  '--color-border-accent-soft': nativeTheme.light.colorBorderAccentSoft,
  '--color-border-strong': nativeTheme.light.colorBorderStrong,
  '--color-border-subtle': nativeTheme.light.colorBorderSubtle,
  '--color-border-tab-blur': nativeTheme.light.colorBorderTabBlur,
  '--color-border-violet': nativeTheme.light.colorBorderViolet,
  '--color-danger': nativeTheme.light.colorDanger,
  '--color-danger-solid': nativeTheme.light.colorDangerSolid,
  '--color-danger-soft': nativeTheme.light.colorBgDangerSoft,
  '--color-overlay-frost': nativeTheme.light.colorOverlayFrost,
  '--color-overlay-scrim': nativeTheme.light.colorOverlayScrim,
  '--color-press-overlay-slate-100-50': nativeTheme.light.colorPressOverlaySlate10050,
  '--color-state-layer-accent': nativeTheme.light.colorStateLayerAccent,
  '--color-state-layer-strong': nativeTheme.light.colorStateLayerStrong,
  '--color-text-accent': nativeTheme.light.colorTextAccent,
  '--color-text-accent-strong': nativeTheme.light.colorTextAccentStrong,
  '--color-text-danger': nativeTheme.light.colorTextDanger,
  '--color-text-disabled': nativeTheme.light.colorTextDisabled,
  '--color-text-muted': nativeTheme.light.colorTextMuted,
  '--color-text-on-accent': nativeTheme.light.colorTextOnAccent,
  '--color-text-primary': nativeTheme.light.colorTextPrimary,
  '--color-text-secondary': nativeTheme.light.colorTextSecondary,
  '--color-text-tertiary': nativeTheme.light.colorTextTertiary,
  '--color-text-toast': nativeTheme.light.colorTextToast,
  '--color-text-violet': nativeTheme.light.colorTextViolet,
  '--color-text-violet-muted': nativeTheme.light.colorTextVioletMuted,
  '--emerald-50': nativeTheme.light.emerald50,
  '--emerald-500': nativeTheme.light.emerald500,
  '--red-50': nativeTheme.light.red50,
  '--red-500': nativeTheme.light.red500,
  '--red-600': nativeTheme.light.red600,
  '--slate-50': nativeTheme.light.slate50,
  '--slate-100': nativeTheme.light.slate100,
  '--slate-200': nativeTheme.light.slate200,
  '--slate-300': nativeTheme.light.slate300,
  '--slate-400': nativeTheme.light.slate400,
  '--slate-500': nativeTheme.light.slate500,
  '--slate-600': nativeTheme.light.slate600,
  '--slate-700': nativeTheme.light.slate700,
  '--teal-50': nativeTheme.light.teal50,
  '--violet-50': nativeTheme.light.violet50,
  '--violet-300': nativeTheme.light.violet300,
  '--violet-400': nativeTheme.light.violet400,
  '--violet-500': nativeTheme.light.violet500,
};

export function resolveThemeValue(value) {
  if (typeof value !== 'string') {
    return value;
  }

  const match = /^var\((--[^),\s]+)(?:,\s*([^)]+))?\)$/.exec(value.trim());
  if (!match) {
    return nativeCssVariables[value] ?? value;
  }

  return nativeCssVariables[match[1]] ?? match[2]?.trim() ?? value;
}

export function getThemeCssVariables(colorMode = 'light') {
  if (colorMode === 'dark') {
    return {
      backgroundColor: nativeTheme.dark.colorBgApp,
    };
  }

  return {
    backgroundColor: nativeTheme.light.colorBgApp,
  };
}
